// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn10fHSbIxFDQm2QYLlcgnNF2gHW7ac7A',
    appId: '1:649126556774:web:f4aff009d32a1917d669a7',
    messagingSenderId: '649126556774',
    projectId: 'shoop-47480',
    authDomain: 'shoop-47480.firebaseapp.com',
    storageBucket: 'shoop-47480.appspot.com',
    measurementId: 'G-YWF646MTL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeULhnbEY60u9ibo7S5nTnHX7sTqhwbI',
    appId: '1:649126556774:android:6260dc91b9645922d669a7',
    messagingSenderId: '649126556774',
    projectId: 'shoop-47480',
    storageBucket: 'shoop-47480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD24OuB1FjW5_qG4Y1MZ9M3nbvfelTQGaY',
    appId: '1:649126556774:ios:39d0cde440f05b80d669a7',
    messagingSenderId: '649126556774',
    projectId: 'shoop-47480',
    storageBucket: 'shoop-47480.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD24OuB1FjW5_qG4Y1MZ9M3nbvfelTQGaY',
    appId: '1:649126556774:ios:39d0cde440f05b80d669a7',
    messagingSenderId: '649126556774',
    projectId: 'shoop-47480',
    storageBucket: 'shoop-47480.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn10fHSbIxFDQm2QYLlcgnNF2gHW7ac7A',
    appId: '1:649126556774:web:fb6e651649663365d669a7',
    messagingSenderId: '649126556774',
    projectId: 'shoop-47480',
    authDomain: 'shoop-47480.firebaseapp.com',
    storageBucket: 'shoop-47480.appspot.com',
    measurementId: 'G-Q450KGSH3L',
  );
}
